{
 "title": "ETH Docker Logs",
 "description": "Easily view the last x minutes of logs from ETH Docker (https://eth-docker.net/)  containers via Loki data source",
 "tags": [ "eth" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Execution Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"eth1\"}"
    }
   ]
  },
  {
   "title": "Consensus Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container_name=\"eth2\"}"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container_name=~\".+-validator-1\"}"
    }
   ]
  },
  {
   "title": "MEV Boost Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{container_name=~\".+-mev-boost-1\"}"
    }
   ]
  }
 ]
}