groups:
  - name: alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 80% on {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 80% on {{ $labels.instance }}"

      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "Instance {{ $labels.instance }} is down"

      ##############################################################################
                            # Blockchain alerts #
      ##############################################################################

      - alert: NumberOfPeersLow (Execution Client)
        expr: p2p_peers < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low number of peers on {{ $labels.instance }} from Execution Client"
          description: "Number of peers is low on {{ $labels.instance }} from Execution Client"

      - alert: NumberOfPeersLow (Consensus Client)
        expr: p2p_peer_count{state="Connected"}  < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low number of peers on {{ $labels.instance }} from Consensus Client"
          description: "Number of peers is low on {{ $labels.instance }} from Consensus Client"
