---
- name: Copy docker-compose to directories
  ansible.builtin.template:
    src: 'docker-compose.yaml.j2'
    dest: '{{ ethnode_data_dir }}/docker-compose.yaml'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0600'
  when: not ansible_check_mode


# - name: Run Eth node service
#   ansible.builtin.command: |
#     chdir={{ ethnode_data_dir }}
#     docker compose -f docker-compose.yaml up -d --force-recreate
#   changed_when: false
#   when: not ansible_check_mode
